# Form implementation generated from reading ui file '.\AdminWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWind(object):
    def setupUi(self, AdminWind):
        AdminWind.setObjectName("AdminWind")
        AdminWind.resize(210, 170)
        AdminWind.setMinimumSize(QtCore.QSize(210, 170))
        AdminWind.setMaximumSize(QtCore.QSize(210, 170))
        self.centralwidget = QtWidgets.QWidget(parent=AdminWind)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 190, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 80, 170, 30))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 120, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        AdminWind.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminWind)
        QtCore.QMetaObject.connectSlotsByName(AdminWind)

    def retranslateUi(self, AdminWind):
        _translate = QtCore.QCoreApplication.translate
        AdminWind.setWindowTitle(_translate("AdminWind", "AdminWind"))
        self.pushButton.setText(_translate("AdminWind", "Открыть терминал"))
        self.label.setText(_translate("AdminWind", "Ты Админ НЕ ЗАБУДЬ!"))
        self.pushButton_2.setText(_translate("AdminWind", "Открыть таблицу"))
