# Form implementation generated from reading ui file '.\AutorizationWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Autorizations(object):
    def setupUi(self, Autorizations):
        Autorizations.setObjectName("Autorizations")
        Autorizations.resize(170, 190)
        Autorizations.setMinimumSize(QtCore.QSize(170, 190))
        Autorizations.setMaximumSize(QtCore.QSize(170, 190))
        self.centralwidget = QtWidgets.QWidget(parent=Autorizations)
        self.centralwidget.setObjectName("centralwidget")
        self.L_Login = QtWidgets.QLabel(parent=self.centralwidget)
        self.L_Login.setGeometry(QtCore.QRect(10, 10, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        self.L_Login.setFont(font)
        self.L_Login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_Login.setObjectName("L_Login")
        self.LE_Login = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.LE_Login.setGeometry(QtCore.QRect(10, 40, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LE_Login.setFont(font)
        self.LE_Login.setObjectName("LE_Login")
        self.L_Password = QtWidgets.QLabel(parent=self.centralwidget)
        self.L_Password.setGeometry(QtCore.QRect(10, 80, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        self.L_Password.setFont(font)
        self.L_Password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_Password.setObjectName("L_Password")
        self.LE_Password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.LE_Password.setGeometry(QtCore.QRect(10, 110, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LE_Password.setFont(font)
        self.LE_Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LE_Password.setObjectName("LE_Password")
        self.PB_Login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Login.setGeometry(QtCore.QRect(10, 150, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PB_Login.setFont(font)
        self.PB_Login.setObjectName("PB_Login")
        Autorizations.setCentralWidget(self.centralwidget)

        self.retranslateUi(Autorizations)
        QtCore.QMetaObject.connectSlotsByName(Autorizations)

    def retranslateUi(self, Autorizations):
        _translate = QtCore.QCoreApplication.translate
        Autorizations.setWindowTitle(_translate("Autorizations", "Autorizations"))
        self.L_Login.setText(_translate("Autorizations", "Логин"))
        self.L_Password.setText(_translate("Autorizations", "Пароль"))
        self.PB_Login.setText(_translate("Autorizations", "Войти"))
