# Form implementation generated from reading ui file '.\ManajerWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Manajer(object):
    def setupUi(self, Manajer):
        Manajer.setObjectName("Manajer")
        Manajer.resize(910, 130)
        Manajer.setMinimumSize(QtCore.QSize(910, 130))
        Manajer.setMaximumSize(QtCore.QSize(910, 130))
        font = QtGui.QFont()
        font.setPointSize(14)
        Manajer.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=Manajer)
        self.centralwidget.setObjectName("centralwidget")
        self.CB_Table = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CB_Table.setGeometry(QtCore.QRect(90, 10, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CB_Table.setFont(font)
        self.CB_Table.setObjectName("CB_Table")
        self.L_Tabl = QtWidgets.QLabel(parent=self.centralwidget)
        self.L_Tabl.setGeometry(QtCore.QRect(10, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.L_Tabl.setFont(font)
        self.L_Tabl.setObjectName("L_Tabl")
        self.PB_Open = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Open.setGeometry(QtCore.QRect(270, 10, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PB_Open.setFont(font)
        self.PB_Open.setObjectName("PB_Open")
        self.PB_Add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Add.setGeometry(QtCore.QRect(370, 10, 180, 30))
        self.PB_Add.setObjectName("PB_Add")
        self.PB_Delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Delete.setGeometry(QtCore.QRect(550, 10, 180, 30))
        self.PB_Delete.setObjectName("PB_Delete")
        self.PB_Update = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Update.setGeometry(QtCore.QRect(730, 10, 180, 30))
        self.PB_Update.setObjectName("PB_Update")
        self.CB_Querry = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CB_Querry.setGeometry(QtCore.QRect(10, 50, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CB_Querry.setFont(font)
        self.CB_Querry.setObjectName("CB_Querry")
        self.PB_Ex_Querry = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Ex_Querry.setGeometry(QtCore.QRect(10, 90, 900, 30))
        self.PB_Ex_Querry.setObjectName("PB_Ex_Querry")
        Manajer.setCentralWidget(self.centralwidget)

        self.retranslateUi(Manajer)
        QtCore.QMetaObject.connectSlotsByName(Manajer)

    def retranslateUi(self, Manajer):
        _translate = QtCore.QCoreApplication.translate
        Manajer.setWindowTitle(_translate("Manajer", "Сотрудник"))
        self.L_Tabl.setText(_translate("Manajer", "Таблицы"))
        self.PB_Open.setText(_translate("Manajer", "Открыть"))
        self.PB_Add.setText(_translate("Manajer", "Добавить данные"))
        self.PB_Delete.setText(_translate("Manajer", "Удалить запись"))
        self.PB_Update.setText(_translate("Manajer", "Обновить данные"))
        self.PB_Ex_Querry.setText(_translate("Manajer", "Выполнить запрос"))
