# Form implementation generated from reading ui file '.\ManajerWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Manajer(object):
    def setupUi(self, Manajer):
        Manajer.setObjectName("Manajer")
        Manajer.resize(350, 130)
        Manajer.setMinimumSize(QtCore.QSize(350, 130))
        Manajer.setMaximumSize(QtCore.QSize(350, 130))
        self.centralwidget = QtWidgets.QWidget(parent=Manajer)
        self.centralwidget.setObjectName("centralwidget")
        self.LB_Fam = QtWidgets.QLabel(parent=self.centralwidget)
        self.LB_Fam.setGeometry(QtCore.QRect(10, 10, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LB_Fam.setFont(font)
        self.LB_Fam.setObjectName("LB_Fam")
        self.LB_Fam_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.LB_Fam_2.setGeometry(QtCore.QRect(10, 50, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LB_Fam_2.setFont(font)
        self.LB_Fam_2.setObjectName("LB_Fam_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 90, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 90, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        Manajer.setCentralWidget(self.centralwidget)

        self.retranslateUi(Manajer)
        QtCore.QMetaObject.connectSlotsByName(Manajer)

    def retranslateUi(self, Manajer):
        _translate = QtCore.QCoreApplication.translate
        Manajer.setWindowTitle(_translate("Manajer", "Сотрудник"))
        self.LB_Fam.setText(_translate("Manajer", "По вежлевее с клиентами"))
        self.LB_Fam_2.setText(_translate("Manajer", "Список запросов"))
        self.pushButton.setText(_translate("Manajer", "Выполнить"))
