# Form implementation generated from reading ui file '.\UpdateInsertWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdateInsert(object):
    def setupUi(self, UpdateInsert):
        UpdateInsert.setObjectName("UpdateInsert")
        UpdateInsert.resize(1000, 470)
        UpdateInsert.setMinimumSize(QtCore.QSize(1000, 470))
        UpdateInsert.setMaximumSize(QtCore.QSize(1000, 470))
        self.centralwidget = QtWidgets.QWidget(parent=UpdateInsert)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 980, 420))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 440, 980, 30))
        self.pushButton.setObjectName("pushButton")
        UpdateInsert.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpdateInsert)
        QtCore.QMetaObject.connectSlotsByName(UpdateInsert)

    def retranslateUi(self, UpdateInsert):
        _translate = QtCore.QCoreApplication.translate
        UpdateInsert.setWindowTitle(_translate("UpdateInsert", "UpdateInsert"))
        self.pushButton.setText(_translate("UpdateInsert", "Выполнить"))
