# Form implementation generated from reading ui file '.\UpdateInsertWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpIn(object):
    def setupUi(self, UpIn):
        UpIn.setObjectName("UpIn")
        UpIn.resize(880, 500)
        UpIn.setMinimumSize(QtCore.QSize(880, 500))
        UpIn.setMaximumSize(QtCore.QSize(880, 500))
        self.centralwidget = QtWidgets.QWidget(parent=UpIn)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 860, 440))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 460, 860, 30))
        self.pushButton.setObjectName("pushButton")
        UpIn.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpIn)
        QtCore.QMetaObject.connectSlotsByName(UpIn)

    def retranslateUi(self, UpIn):
        _translate = QtCore.QCoreApplication.translate
        UpIn.setWindowTitle(_translate("UpIn", "UpIn"))
        self.pushButton.setText(_translate("UpIn", "Выполнить"))
