# Form implementation generated from reading ui file '.\UserWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(250, 190)
        UserWindow.setMinimumSize(QtCore.QSize(250, 190))
        UserWindow.setMaximumSize(QtCore.QSize(250, 190))
        self.centralwidget = QtWidgets.QWidget(parent=UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LB_Fam = QtWidgets.QLabel(parent=self.centralwidget)
        self.LB_Fam.setGeometry(QtCore.QRect(10, 10, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LB_Fam.setFont(font)
        self.LB_Fam.setObjectName("LB_Fam")
        self.LB_Nam = QtWidgets.QLabel(parent=self.centralwidget)
        self.LB_Nam.setGeometry(QtCore.QRect(10, 40, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LB_Nam.setFont(font)
        self.LB_Nam.setObjectName("LB_Nam")
        self.LB_Otch = QtWidgets.QLabel(parent=self.centralwidget)
        self.LB_Otch.setGeometry(QtCore.QRect(10, 70, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LB_Otch.setFont(font)
        self.LB_Otch.setObjectName("LB_Otch")
        self.PB_Schet = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Schet.setGeometry(QtCore.QRect(10, 100, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PB_Schet.setFont(font)
        self.PB_Schet.setObjectName("PB_Schet")
        self.PB_Oper = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Oper.setGeometry(QtCore.QRect(130, 100, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PB_Oper.setFont(font)
        self.PB_Oper.setObjectName("PB_Oper")
        self.PB_Info = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_Info.setGeometry(QtCore.QRect(10, 140, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PB_Info.setFont(font)
        self.PB_Info.setObjectName("PB_Info")
        UserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "Пользователь"))
        self.LB_Fam.setText(_translate("UserWindow", "Фамилия"))
        self.LB_Nam.setText(_translate("UserWindow", "Имя"))
        self.LB_Otch.setText(_translate("UserWindow", "Отчество"))
        self.PB_Schet.setText(_translate("UserWindow", "Счета"))
        self.PB_Oper.setText(_translate("UserWindow", "Операции"))
        self.PB_Info.setText(_translate("UserWindow", "О клиенте"))
