# Form implementation generated from reading ui file '.\VievWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VievWindow(object):
    def setupUi(self, VievWindow):
        VievWindow.setObjectName("VievWindow")
        VievWindow.resize(1000, 450)
        VievWindow.setMinimumSize(QtCore.QSize(1000, 450))
        VievWindow.setMaximumSize(QtCore.QSize(1000, 450))
        self.centralwidget = QtWidgets.QWidget(parent=VievWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 980, 420))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        VievWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(VievWindow)
        QtCore.QMetaObject.connectSlotsByName(VievWindow)

    def retranslateUi(self, VievWindow):
        _translate = QtCore.QCoreApplication.translate
        VievWindow.setWindowTitle(_translate("VievWindow", "VievWindow"))
